//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs.Storage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursDbEntities : DbContext
    {
        public KursDbEntities()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DigitalCamera> DigitalCameras { get; set; }
        public virtual DbSet<Maker> Makers { get; set; }
        public virtual DbSet<OperatingSystem> OperatingSystems { get; set; }
        public virtual DbSet<Processor> Processors { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<ScreenResolution> ScreenResolutions { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
