//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kurs.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.Reviews = new HashSet<Review>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Model { get; set; }
        public Nullable<double> Heigth { get; set; }
        public Nullable<double> Width { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public int MakerId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> ScreenResolutionId { get; set; }
        public Nullable<int> OperatingSystemId { get; set; }
        public Nullable<int> ProcessorId { get; set; }
        public Nullable<int> Ram { get; set; }
        public Nullable<int> Memory { get; set; }
        public Nullable<int> DigitalCameraId { get; set; }
        public string Info { get; set; }
        public string Image { get; set; }
        public int TotalCount { get; set; }
        public int FreeCount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual Country Country { get; set; }
        public virtual DigitalCamera DigitalCamera { get; set; }
        public virtual Maker Maker { get; set; }
        public virtual OperatingSystem OperatingSystem { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual ScreenResolution ScreenResolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
